-- ============================================
-- SIMPLIFIED APPOINTMENTS WITH EMR ACCESS
-- Single table combining appointments and EMR access control
-- ============================================

-- Drop old tables if they exist
DROP TABLE IF EXISTS pet_emr_access CASCADE;
DROP TABLE IF EXISTS hospitals_appointments CASCADE;

-- Single unified appointments table with EMR access control
CREATE TABLE hospitals_appointments (
  -- Primary key
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_number TEXT UNIQUE,
  
  -- Pet reference
  pet_platform_id TEXT NOT NULL, -- A01xxxxxx
  
  -- Owner reference
  owner_user_platform_id TEXT NOT NULL, -- H00xxxxxx
  
  -- Entity reference (physical location: hospital, store, clinic, etc.)
  entity_platform_id TEXT NOT NULL, -- E01xxxxxx
  
  -- Doctor reference
  doctor_user_platform_id TEXT, -- H00xxxxxx
  
  -- Booking information
  booking_source TEXT DEFAULT 'owner-self', -- owner-self, hospital-phone, hospital-walkin, hospital-online
  booked_by_user_platform_id TEXT, -- H00xxxxxx (staff member who created appointment)
  
  -- Appointment details
  appointment_date DATE NOT NULL,
  appointment_time TIME NOT NULL,
  duration_minutes INTEGER DEFAULT 30,
  appointment_type TEXT DEFAULT 'routine', -- routine, emergency, follow-up, vaccination, surgery, dental, grooming
  status TEXT DEFAULT 'scheduled', -- scheduled, confirmed, in-progress, completed, cancelled, no-show
  reason TEXT,
  notes TEXT,
  
  -- EMR Access Control (OTP-based access granting)
  emr_access_granted BOOLEAN DEFAULT false,
  emr_otp_code TEXT, -- 6-digit OTP generated by owner or system
  emr_otp_verified BOOLEAN DEFAULT false,
  emr_otp_verified_at TIMESTAMPTZ,
  emr_otp_expires_at TIMESTAMPTZ, -- OTP valid for 24 hours
  emr_otp_sent_to_owner BOOLEAN DEFAULT false, -- True if OTP sent via SMS/email to owner
  emr_otp_sent_at TIMESTAMPTZ, -- When OTP was sent to owner
  
  -- Write Access Control (during active consultation)
  emr_write_access_active BOOLEAN DEFAULT false,
  emr_write_access_started_at TIMESTAMPTZ, -- When consultation began
  emr_write_access_ended_at TIMESTAMPTZ, -- When consultation completed
  
  -- Permanent Read Access (hospital always retains read access after first consultation)
  emr_read_access_granted_at TIMESTAMPTZ, -- When hospital first verified OTP
  
  -- Access Revocation (if owner wants to revoke all access)
  emr_access_revoked BOOLEAN DEFAULT false,
  emr_access_revoked_at TIMESTAMPTZ,
  emr_access_revoked_by UUID,
  emr_revocation_reason TEXT,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Add foreign key constraints conditionally (only if referenced tables have unique constraints on platform_id)
-- Platform IDs are the primary reference, UUIDs are optional
-- Naming convention: 
--   user_platform_id (all users: owners, doctors, staff, etc.)
--   pet_platform_id (pets)
--   organization_platform_id (companies that pay/subscribe)
--   entity_platform_id (physical locations: hospitals, stores, clinics where business is conducted)

-- Constraint 1: pet_platform_id -> pet_master(pet_platform_id)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE table_name = 'pet_master' 
    AND constraint_type IN ('PRIMARY KEY', 'UNIQUE')
    AND constraint_name LIKE '%platform_id%'
  ) THEN
    ALTER TABLE hospitals_appointments
      ADD CONSTRAINT fk_appointments_pet_platform 
      FOREIGN KEY (pet_platform_id) 
      REFERENCES pet_master(pet_platform_id) 
      ON DELETE CASCADE;
  END IF;
END $$;

-- Constraint 2: owner_user_platform_id -> profiles(user_platform_id)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE table_name = 'profiles' 
    AND constraint_type IN ('PRIMARY KEY', 'UNIQUE')
    AND constraint_name LIKE '%user_platform_id%'
  ) THEN
    ALTER TABLE hospitals_appointments
      ADD CONSTRAINT fk_appointments_owner_user_platform 
      FOREIGN KEY (owner_user_platform_id) 
      REFERENCES profiles(user_platform_id) 
      ON DELETE CASCADE;
  END IF;
END $$;

-- Constraint 3: entity_platform_id -> entities(entity_platform_id)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE table_name = 'entities' 
    AND constraint_type IN ('PRIMARY KEY', 'UNIQUE')
    AND constraint_name LIKE '%entity_platform_id%'
  ) THEN
    ALTER TABLE hospitals_appointments
      ADD CONSTRAINT fk_appointments_entity_platform 
      FOREIGN KEY (entity_platform_id) 
      REFERENCES entities(entity_platform_id) 
      ON DELETE CASCADE;
  END IF;
END $$;

-- Constraint 4: doctor_user_platform_id -> profiles(user_platform_id)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE table_name = 'profiles' 
    AND constraint_type IN ('PRIMARY KEY', 'UNIQUE')
    AND constraint_name LIKE '%user_platform_id%'
  ) THEN
    ALTER TABLE hospitals_appointments
      ADD CONSTRAINT fk_appointments_doctor_user_platform 
      FOREIGN KEY (doctor_user_platform_id) 
      REFERENCES profiles(user_platform_id) 
      ON DELETE SET NULL;
  END IF;
END $$;

-- Constraint 5: booked_by_user_platform_id -> profiles(user_platform_id)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE table_name = 'profiles' 
    AND constraint_type IN ('PRIMARY KEY', 'UNIQUE')
    AND constraint_name LIKE '%user_platform_id%'
  ) THEN
    ALTER TABLE hospitals_appointments
      ADD CONSTRAINT fk_appointments_booked_by_user_platform 
      FOREIGN KEY (booked_by_user_platform_id) 
      REFERENCES profiles(user_platform_id) 
      ON DELETE SET NULL;
  END IF;
END $$;

-- Indexes for performance
CREATE INDEX idx_appointments_pet_platform_id ON hospitals_appointments(pet_platform_id);
CREATE INDEX idx_appointments_owner_user_platform_id ON hospitals_appointments(owner_user_platform_id);
CREATE INDEX idx_appointments_entity_platform_id ON hospitals_appointments(entity_platform_id);
CREATE INDEX idx_appointments_doctor_user_platform_id ON hospitals_appointments(doctor_user_platform_id);
CREATE INDEX idx_appointments_date ON hospitals_appointments(appointment_date);
CREATE INDEX idx_appointments_status ON hospitals_appointments(status);

-- Function to generate appointment number (format: APT-YYYYMMDD-XXXX)
CREATE OR REPLACE FUNCTION generate_appointment_number()
RETURNS TEXT AS $$
DECLARE
  date_part TEXT;
  sequence_part TEXT;
  new_number TEXT;
BEGIN
  date_part := TO_CHAR(CURRENT_DATE, 'YYYYMMDD');
  
  -- Get the count of appointments today and increment
  SELECT LPAD((COUNT(*) + 1)::TEXT, 4, '0')
  INTO sequence_part
  FROM hospital_master_appointments
  WHERE appointment_date = CURRENT_DATE;
  
  new_number := 'APT-' || date_part || '-' || sequence_part;
  
  RETURN new_number;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-generate appointment number
CREATE OR REPLACE FUNCTION set_appointment_number()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.appointment_number IS NULL THEN
    NEW.appointment_number := generate_appointment_number();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_appointment_number
  BEFORE INSERT ON hospitals_appointments
  FOR EACH ROW
  EXECUTE FUNCTION set_appointment_number();

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_appointments_updated_at
  BEFORE UPDATE ON hospitals_appointments
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- RLS (Row Level Security) Policies
ALTER TABLE hospitals_appointments ENABLE ROW LEVEL SECURITY;

-- Policy: Allow all operations for anon role (development)
CREATE POLICY dev_all_anon ON hospitals_appointments
  FOR ALL
  TO anon
  USING (true)
  WITH CHECK (true);

-- Policy: Allow all operations for authenticated users (production)
CREATE POLICY authenticated_all ON hospitals_appointments
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Comments for documentation
COMMENT ON TABLE hospitals_appointments IS 'Appointments with integrated EMR access control';
COMMENT ON COLUMN hospitals_appointments.booking_source IS 'How appointment was created: owner-self, hospital-phone, hospital-walkin, hospital-online';
COMMENT ON COLUMN hospitals_appointments.booked_by IS 'Staff member who created appointment (NULL if owner self-booked)';
COMMENT ON COLUMN hospitals_appointments.emr_otp_code IS 'OTP generated for EMR access (by owner or sent to owner)';
COMMENT ON COLUMN hospitals_appointments.emr_otp_sent_to_owner IS 'True if system sent OTP to owner via SMS/email';
COMMENT ON COLUMN hospitals_appointments.emr_write_access_active IS 'True during active consultation, allows hospital to write to EMR';
COMMENT ON COLUMN hospitals_appointments.emr_read_access_granted_at IS 'Hospital retains permanent read access after first verification';
COMMENT ON COLUMN hospitals_appointments.emr_access_revoked IS 'Owner can revoke all access if needed';

-- ============================================
-- HOSPITAL EMR ACCESS VIEW
-- Simplified view showing which hospital_master have access to which pets
-- ============================================

CREATE OR REPLACE VIEW hospital_pet_emr_access AS
SELECT DISTINCT ON (pet_platform_id, entity_platform_id)
  pet_platform_id,
  entity_platform_id,
  owner_user_platform_id,
  -- Access status
  CASE
    WHEN emr_access_revoked THEN 'revoked'
    WHEN emr_write_access_active THEN 'read-write'
    WHEN emr_otp_verified THEN 'read-only'
    ELSE 'pending'
  END as access_type,
  emr_otp_verified as is_verified,
  emr_access_revoked as is_revoked,
  emr_write_access_active as has_write_access,
  -- Timestamps
  emr_read_access_granted_at as access_granted_at,
  emr_write_access_started_at as write_started_at,
  emr_write_access_ended_at as write_ended_at,
  emr_access_revoked_at as revoked_at,
  -- Last appointment with this entity
  id as last_appointment_id,
  appointment_date as last_appointment_date,
  created_at
FROM hospital_master_appointments
WHERE emr_otp_verified = true -- Only include verified access
ORDER BY pet_platform_id, entity_platform_id, created_at DESC;

COMMENT ON VIEW hospital_pet_emr_access IS 'Shows which hospital_master have EMR access to which pets (simplified view)';

-- ============================================
-- SAMPLE DATA (Optional - for testing)
-- ============================================

-- Uncomment to insert sample data for testing:
/*
-- Sample appointment with pending EMR access
INSERT INTO hospitals_appointments (
  pet_id,
  pet_platform_id,
  owner_id,
  owner_platform_id,
  hospital_id,
  hospital_platform_id,
  doctor_id,
  doctor_platform_id,
  appointment_date,
  appointment_time,
  appointment_type,
  status,
  reason,
  emr_otp_code,
  emr_otp_expires_at
) VALUES (
  '00000000-0000-0000-0000-000000000001', -- Replace with real pet_id
  'A01abc123',
  '00000000-0000-0000-0000-000000000002', -- Replace with real owner_id
  'H00xyz789',
  '00000000-0000-0000-0000-000000000003', -- Replace with real hospital_id
  'E01hos001',
  '00000000-0000-0000-0000-000000000004', -- Replace with real doctor_id
  'H00doc001',
  '2025-10-20',
  '10:00:00',
  'routine',
  'scheduled',
  'Annual checkup',
  '123456', -- OTP code
  now() + interval '24 hours' -- OTP expires in 24 hours
);
*/
