import { Service, ServiceCategory, ServiceStatus } from '@/types';

export const FURFIELD_SERVICES: Service[] = [
  {
    id: 'ff-hms-6900',
    name: 'HMS Gateway',
    url: process.env.NEXT_PUBLIC_HMS_SERVICE_URL || 'http://localhost:6900',
    port: 6900,
    status: ServiceStatus.CHECKING,
    description: 'Unified gateway, reverse proxy, and dashboard for HMS modules',
    icon: '🏠',
    category: ServiceCategory.MANAGEMENT,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-plat-6600',
    name: 'Platform Administration',
    url: process.env.NEXT_PUBLIC_PLATFORM_SERVICE_URL || 'http://localhost:6600',
    port: 6600,
    status: ServiceStatus.CHECKING,
    description: 'Platform configuration, tenant management, and feature controls',
    icon: '🛠️',
    category: ServiceCategory.MANAGEMENT,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-orgn-6700',
    name: 'Organization Management',
    url: process.env.NEXT_PUBLIC_ORGN_SERVICE_URL || 'http://localhost:6700',
    port: 6700,
    status: ServiceStatus.CHECKING,
    description: 'Organization structure, departments, and facility management',
    icon: '🏢',
    category: ServiceCategory.MANAGEMENT,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-outp-6830',
    name: 'Outpatient Service',
    url: process.env.NEXT_PUBLIC_OUTP_SERVICE_URL || 'http://localhost:6830',
    port: 6830,
    status: ServiceStatus.CHECKING,
    description: 'Ambulatory patient care, appointments, and consultations',
    icon: '🩺',
    category: ServiceCategory.HEALTHCARE,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-inpa-6831',
    name: 'Inpatient Service',
    url: process.env.NEXT_PUBLIC_INPA_SERVICE_URL || 'http://localhost:6831',
    port: 6831,
    status: ServiceStatus.CHECKING,
    description: 'Admissions, ward management, and discharge workflows',
    icon: '🏨',
    category: ServiceCategory.HEALTHCARE,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-diag-6832',
    name: 'Diagnostics Service',
    url: process.env.NEXT_PUBLIC_DIAG_SERVICE_URL || 'http://localhost:6832',
    port: 6832,
    status: ServiceStatus.CHECKING,
    description: 'Laboratory, imaging, and diagnostic reporting',
    icon: '🔬',
    category: ServiceCategory.HEALTHCARE,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-oper-6833',
    name: 'Operation Theater Service',
    url: process.env.NEXT_PUBLIC_OPER_SERVICE_URL || 'http://localhost:6833',
    port: 6833,
    status: ServiceStatus.CHECKING,
    description: 'Surgery scheduling, procedures, and OT workflows',
    icon: '🏥',
    category: ServiceCategory.HEALTHCARE,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-phar-6834',
    name: 'Pharmacy Service',
    url: process.env.NEXT_PUBLIC_PHAR_SERVICE_URL || 'http://localhost:6834',
    port: 6834,
    status: ServiceStatus.CHECKING,
    description: 'Medication inventory, dispensing, and procurement',
    icon: '💊',
    category: ServiceCategory.HEALTHCARE,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-faci-6840',
    name: 'Facility Operations',
    url: process.env.NEXT_PUBLIC_FACI_SERVICE_URL || 'http://localhost:6840',
    port: 6840,
    status: ServiceStatus.CHECKING,
    description: 'Facility dashboards, work orders, and compliance tracking',
    icon: '🏢',
    category: ServiceCategory.MANAGEMENT,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-anal-6820',
    name: 'Analytics & Reporting',
    url: process.env.NEXT_PUBLIC_ANALYTICS_SERVICE_URL || 'http://localhost:6820',
    port: 6820,
    status: ServiceStatus.CHECKING,
    description: 'Cross-service dashboards, KPIs, and scheduled reporting',
    icon: '📊',
    category: ServiceCategory.MANAGEMENT,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-finm-6850',
    name: 'Financial Management',
    url: process.env.NEXT_PUBLIC_FINM_SERVICE_URL || 'http://localhost:6850',
    port: 6850,
    status: ServiceStatus.CHECKING,
    description: 'Financial operations, billing, and analytics',
    icon: '💰',
    category: ServiceCategory.FINANCIAL,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-hrms-6860',
    name: 'HR & Rostering',
    url: process.env.NEXT_PUBLIC_HRMS_SERVICE_URL || 'http://localhost:6860',
    port: 6860,
    status: ServiceStatus.CHECKING,
    description: 'Employee management, rostering, and workforce planning',
    icon: '👥',
    category: ServiceCategory.HR,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-purc-6870',
    name: 'Purchasing Service',
    url: process.env.NEXT_PUBLIC_PURC_SERVICE_URL || 'http://localhost:6870',
    port: 6870,
    status: ServiceStatus.CHECKING,
    description: 'Procurement workflows, supplier management, and contracts',
    icon: '🛒',
    category: ServiceCategory.FINANCIAL,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-chat-6880',
    name: 'Chat & Communication',
    url: process.env.NEXT_PUBLIC_CHAT_SERVICE_URL || 'http://localhost:6880',
    port: 6880,
    status: ServiceStatus.CHECKING,
    description: 'Real-time staff communication and channel management',
    icon: '💬',
    category: ServiceCategory.MANAGEMENT,
    healthEndpoint: '/api/health',
  },
  {
    id: 'ff-docs-6899',
    name: 'Documentation Service',
    url: process.env.NEXT_PUBLIC_DOCS_SERVICE_URL || 'http://localhost:6899',
    port: 6899,
    status: ServiceStatus.CHECKING,
    description: 'Documentation, knowledge management, and developer guides',
    icon: '📚',
    category: ServiceCategory.DOCUMENTATION,
    healthEndpoint: '/api/health',
  },
];

export const getServicesByCategory = (category: ServiceCategory): Service[] => {
  return FURFIELD_SERVICES.filter(service => service.category === category);
};

export const getServiceById = (id: string): Service | undefined => {
  return FURFIELD_SERVICES.find(service => service.id === id);
};

export const getServiceByPort = (port: number): Service | undefined => {
  return FURFIELD_SERVICES.find(service => service.port === port);
};
